project:
  type: book
  output-dir: docs
  
book:
  title: "The 4 + 1 Model of Data Science"
  reader-mode: true
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - the-four-plus-one-model.qmd
  appendices:
    - appendix-sources.qmd

format:
  html: 
    code-link: true
    author-meta: "Rafael C. Alvarado"
    author-affiliation: "School of Data Science, University of Virginia"
    callout-appearance: simple