project:
  type: book
  output-dir: docs
  
book:
  title: "The 4+1 Model of Data Science"
  reader-mode: true
  author: "Rafael C. Alvarado"
  date: "20 December 2022"
  page-navigation: true
  repo-url: https://github.com/ontoligent/four-plus-one-model

  # downloads: [pdf]
  chapters:
    - index.qmd
    - the-four-plus-one-model.qmd
    - concluding-remarks.qmd
  appendices:
    - appendix-sources.qmd
    - ds-and-ai.qmd

  page-footer:
    left: |
      Written by Rafael C. Alvarado with input from many colleagues at UVA's [School of Data Science](http://datascience.virginia.edu).
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

format:
  html: 
    code-link: true
    callout-appearance: simple
    author-meta: "Rafael C. Alvarado"
    number-sections: false
    fig-align: "center"

  # pdf:
  #   documentclass: scrreport
  # epub:
  #   cover-image: cover.png    