project:
  type: book
  output-dir: docs
  
book:
  title: "The 4 + 1 Model of Data Science"
  reader-mode: true
  author: "Rafael C. Alvarado"
  date: "8 November 2022"
  page-navigation: true
  repo-url: https://github.com/ontoligent/four-plus-one-model

  # downloads: [pdf]
  chapters:
    - index.qmd
    - the-four-plus-one-model.qmd
    - concluding-remarks.qmd
  appendices:
    - appendix-sources.qmd

format:
  html: 
    code-link: true
    callout-appearance: simple
  # pdf:
  #   documentclass: scrreport
  # epub:
  #   cover-image: cover.png    